---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - local.eks-{{ template "cluster-name" . }}.us-west-2.{{.Values.environment}}.egailabs.expedia.com
        - remote.eks-{{ template "cluster-name" . }}.us-west-2.{{.Values.environment}}.egailabs.expedia.com

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}
spec:
  hosts:
    - local.eks-{{ template "cluster-name" . }}.us-west-2.{{.Values.environment}}.egailabs.expedia.com
  gateways:
    - {{.Chart.Name}}
  http:
    - match:
        - uri:
            prefix: /app
      route:
        - destination:
            host: {{.Chart.Name}}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Chart.Name}}-remote
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}-remote
spec:
  hosts:
    - remote.eks-{{ template "cluster-name" . }}.us-west-2.{{.Values.environment}}.egailabs.expedia.com
  gateways:
    - {{.Chart.Name}}
  http:
    - match:
        - uri:
            prefix: /app
      route:
        - destination:
            host: istio-multi-remote.default.global
