---
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Chart.Name}} # this will generate a service with the same name
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 172800  # 48h
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: {{.Chart.Name}}
  service:
    port: 8080
  skipAnalysis: false
  canaryAnalysis:
    # 30s * 5760 = 48h, This time is skipped for each stepping-up if it does not have metrics setup.
    interval: 30s
    threshold: 5760
    # max weight should be bigger than step weight to prevent releasing the new version before release-approval-check returns.
    maxWeight: 10
    stepWeight: 5
    webhooks:
      - name: release-approval-check
        type: rollout
        url: http://webhook.kube-system/release-approvals/check
        timeout: 10s
        metadata:
          token: {{.Values.version}}
      - name: log-release-version
        type: post-rollout
        url: http://webhook.kube-system/released-apps
        timeout: 10s
        metadata:
          token: {{.Values.version}}
