---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - amerigo.{{.Values.clusterName}}.{{.Values.environment}}.egailabs.expedia.com
        - amerigo.{{.Values.clusterName}}.{{.Values.region}}.{{.Values.environment}}.egailabs.expedia.com
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - amerigo.{{.Values.clusterName}}.{{.Values.environment}}.egailabs.expedia.com
        - amerigo.{{.Values.clusterName}}.{{.Values.region}}.{{.Values.environment}}.egailabs.expedia.com

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vpce-{{.Chart.Name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    istio: vpce-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - amerigo.{{.Values.clusterName}}.{{.Values.environment}}.egailabs.expedia.com
        - amerigo.{{.Values.clusterName}}.{{.Values.region}}.{{.Values.environment}}.egailabs.expedia.com
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/vpce-ingressgateway-certs/tls.crt
        privateKey: /etc/istio/vpce-ingressgateway-certs/tls.key
      hosts:
        - amerigo.{{.Values.clusterName}}.egailabs.eglocal.exp-{{.Values.environment}}.net
        - amerigo.{{.Values.clusterName}}.{{.Values.region}}.egailabs.eglocal.exp-{{.Values.environment}}.net

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}
spec:
  hosts:
    - amerigo.{{.Values.clusterName}}.{{.Values.environment}}.egailabs.expedia.com
    - amerigo.{{.Values.clusterName}}.{{.Values.region}}.{{.Values.environment}}.egailabs.expedia.com
    - amerigo.{{.Values.clusterName}}.egailabs.eglocal.exp-{{.Values.environment}}.net
    - amerigo.{{.Values.clusterName}}.{{.Values.region}}.egailabs.eglocal.exp-{{.Values.environment}}.net
  gateways:
    - {{.Chart.Name}}
    - vpce-{{.Chart.Name}}
  http:
    - match:
        - uri:
            prefix: /{{.Chart.Name}}
      route:
        - destination:
            host: {{.Chart.Name}}
            port:
              number: 8080
      mirror:
        host: {{.Chart.Name}}-canary
        port:
          number: 8080
    - match:
        - uri:
            prefix: /{{.Chart.Name}}/canary
      route:
        - destination:
            host: {{.Chart.Name}}-canary
            port:
              number: 8080