---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{.Chart.Name}}.eks-dev-compute2.us-west-2.test.egailabs.expedia.com

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Chart.Name}}-router
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}-router
spec:
  hosts:
    - {{.Chart.Name}}.eks-dev-compute2.us-west-2.test.egailabs.expedia.com
  gateways:
    - {{.Chart.Name}}
  http:
    - route:
        - destination:
            host: "{{.Chart.Name}}"
            port:
              number: 8080
      mirror:
        host: "{{.Chart.Name}}-canary"
        port:
          number: 8080

{{/*---*/}}
{{/*apiVersion: extensions/v1beta1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: {{.Chart.Name}}*/}}
{{/*  namespace: {{.Values.namespace}}*/}}
{{/*  labels:*/}}
{{/*    app: {{.Chart.Name}}*/}}
{{/*  annotations:*/}}
{{/*      {{ if and (.Values.environment) (eq .Values.environment "local") }}*/}}
{{/*    kubernetes.io/ingress.class: nginx*/}}
{{/*    nginx.ingress.kubernetes.io/enable-cors: "true"*/}}
{{/*      {{ else }}*/}}
{{/*    kubernetes.io/ingress.class: traefik*/}}
{{/*    {{ end }}*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*    - host: {{.Chart.Name}}.eks-dev-compute.us-west-2.test.egailabs.expedia.com*/}}
{{/*      http:*/}}
{{/*        port: 80*/}}
{{/*        paths:*/}}
{{/*          - backend:*/}}
{{/*              serviceName: {{.Chart.Name}}-router*/}}
{{/*              servicePort: 8080*/}}
{{/*            path: /*/}}

{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  namespace: {{.Values.namespace}}*/}}
{{/*  name: {{.Chart.Name}}-router*/}}
{{/*  labels:*/}}
{{/*    app: {{.Chart.Name}}-router*/}}
{{/*spec:*/}}
{{/*  type: ExternalName*/}}
{{/*  externalName: {{.Chart.Name}}-router.com*/}}

{{/*---*/}}
{{/*apiVersion: networking.istio.io/v1alpha3*/}}
{{/*kind: VirtualService*/}}
{{/*metadata:*/}}
{{/*  name: {{.Chart.Name}}-router*/}}
{{/*  namespace: {{.Values.namespace}}*/}}
{{/*  labels:*/}}
{{/*    app: {{.Chart.Name}}-router*/}}
{{/*spec:*/}}
{{/*  hosts:*/}}
{{/*    - {{.Chart.Name}}-router*/}}
{{/*  gateways:*/}}
{{/*    - mesh*/}}
{{/*  http:*/}}
{{/*    - route:*/}}
{{/*        - destination:*/}}
{{/*            host: "{{.Chart.Name}}"*/}}
{{/*            port:*/}}
{{/*              number: 8080*/}}
{{/*      mirror:*/}}
{{/*        host: "{{.Chart.Name}}-canary"*/}}
{{/*        port:*/}}
{{/*          number: 8080*/}}